services:
  SOLID_SERVER_S1:
    # image: georgepacheco/solid-server:1.1
    # image: georgepacheco/solid-server:1.3

    # essa imagem já copiava o nginx.conf 
    # image: georgepacheco/dash_solid:1.0

    # versão anterior com problema no https
    # image: georgepacheco/dash-solid:1.2.2

    # versão com tentativa de resolver o https. Criei uma 
    # nova image do solid (1.3.2) para startar https e com os certificados
    # salvos na pasta config/certs. Além disso já tem os dois usuários
    # HomeSimulator e Health (para teste, pois precisará ser alterado
    # quando for levar para o experimento, uma vez que os webIds desses
    # usuários precisam estar de acordo com o endereço do servidor)
    image: georgepacheco/dash-solid:1.2.3

    container_name: SOLID_SERVER_S1
    # env_file:
    #   .env
    volumes:
      - .:/solid-server
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./FotSolid/fot-solid-dash/build:/usr/share/nginx/html/fot-solid-dash
      - ./FotSolid/health-application/build:/usr/share/nginx/html/health-application
      
      - ./FotSolid/certs/server.crt:/etc/nginx/ssl/server.crt
      - ./FotSolid/certs/server.key:/etc/nginx/ssl/server.key
      # - ./nginx/conf/:/etc/nginx/conf.d/:ro
    expose:
      - "3000"    
      - "3030"
      - "3001"
      - "3002"
      - "80"
      - "443"
    ports:
     - "3000:3000"     
     - "3001:3001"
     - "3002:3002"
     - "3030:3030"
     - "80:80"
     - "443:443"
    # restart: always
    networks:
      comm-mqtt:
        aliases:
          - server1.solid
      mqtt-mininet:
        ipv4_address: 222.222.222.9
        aliases:
          - server1.solid        
    # entrypoint: bash -c "npm start -- -b http://192.168.0.111:3000 -c config/file.json -f .data & sleep 20 & python3 ../solid-server/server.py & node ../solid-server/FotSolid/backend/dist/index.js & nginx -c /etc/nginx/nginx.conf -g 'daemon off;'"    
    entrypoint: bash -c "npm start -- -b https://192.168.0.111:3000 -c config/file-https.json -f .data --httpsKey config/certs/server.key --httpsCert config/certs/server.crt & sleep 20 & python3 ../solid-server/server.py & node ../solid-server/FotSolid/backend/dist/index.js & nginx -c /etc/nginx/nginx.conf -g 'daemon off;'"    
    # entrypoint: bash -c "npm start -- -c config/file.json -f .data & sleep 20 & python3 ../solid-server/server.py & node ../solid-server/FotSolid/backend/dist/index.js & nginx -c /etc/nginx/nginx.conf -g 'daemon off;'"    
    
    
networks:
  comm-mqtt:
    name: comm-mqtt
    external: true
  mqtt-mininet:
    name: mqtt-mininet
    external: true
